# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  #config.vm.provision :shell, :path=> "bootstrap.sh"
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file = "bootstrap.pp"
    puppet.module_path = "puppet/modules"
    puppet.options = "--verbose --debug"
  end

  config.vm.hostname = "pybox64"
  config.ssh.guest_port = 22
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 5001, host: 5001
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.network "forwarded_port", guest: 8001, host: 8001
 
  config.vm.provider :virtualbox do |vb|
    vb.gui = true
    vb.customize ["modifyvm", :id, 
                  "--memory", "8128", 
                  "--vram" , "256",
                  "--cpus" , "4",
                  "--ioapic", "on",
                  "--pae", "on",
                  "--hwvirtex", "on",
                  "--largepages", "on",
                  "--accelerate3d", "on",
                  "--monitorcount", "1",
                  "--clipboard", "bidirectional",
                  "--draganddrop", "bidirectional",
                  "--rtcuseutc", "off",
                  "--cpuhotplug", "on",
                  "--cpuexecutioncap", "90",
                  "--longmode", "on",
                  "--nestedpaging", "on"
                  ]
   end
end
