# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "deimosfr/debian-wheezy"
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file = "bootstrap.pp"
    puppet.module_path = "puppet/modules"
    puppet.options = "--verbose --debug"
  end

  config.vm.hostname = "debian-7-64"
  config.ssh.guest_port = 22
 
  config.vm.provider :virtualbox do |vb|
    vb.gui = true
    vb.customize ["modifyvm", :id, 
                  "--memory", "2048", 
                  "--vram" , "128",
                  "--cpus" , "2",
                  "--ioapic", "on",
                  "--pae", "on",
                  "--hwvirtex", "on",
                  "--largepages", "on",
                  "--accelerate3d", "on",
                  "--monitorcount", "1",
                  "--clipboard", "bidirectional",
                  "--draganddrop", "bidirectional",
                  "--rtcuseutc", "off",
                  "--cpuhotplug", "on",
                  "--cpuexecutioncap", "90",
                  "--longmode", "on",
                  "--nestedpaging", "on"
                  ]
   end
end
